config/routes.rb
Rails.application.routes.draw do

  root  'company_addresses#departments'
  get 'signup' => 'users#new'
  get 'reset' => 'users#edit', :as => :reset
  get '/login' => 'sessions#new'
  get '/addresses' => 'company_addresses#index'
  post 'login' => 'sessions#create'
  post 'reset' => 'users#update_password'
  post 'bookmark' => 'bookmarks#create', :as => :bookmark
  post 'unmark' => 'bookmarks#destroy', :as => :unmark
  post '/addresses' => 'company_addresses#index'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :company_addresses

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :company_address, optional: true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :company_addresses
end

app/models/company_address.rb
class CompanyAddress < ApplicationRecord
  belongs_to :company, optional: true
  has_many :users, through: :bookmarks
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :bookmarks
  has_many :company_addresses, through: :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/login' unless current_user
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :require_user, only: [:index, :departments]

  def create
    cpn = CompanyAddress.find(params[:company_address_id])
    @bookmark = Bookmark.create(:company_address => cpn, :user =>current_user)
    flash[:success] = "Address has been added to bookmarks"
  end

  def destroy
    @bookmark = Bookmark.find_by(company_address_id: params[:company_address_id], user_id: current_user.id)
    @bookmark.destroy
    flash[:success] = "Bookmark has been removed"
  end
end

app/controllers/company_addresses_controller.rb
class CompanyAddressesController < ApplicationController
  before_action :require_user, only: [:index, :departments]

  def index
    if params[:zip_codes] && params[:zip_codes].any?
      @addresses = CompanyAddress.joins(:company).select(
          'companies.company_name, companies.company_size, companies.category ,company_addresses.street_number,
        company_addresses.street_indicator, company_addresses.street_type, company_addresses.street_label,
        company_addresses.zip_code, company_addresses.city, company_addresses.latitude, company_addresses.longitude,
        bookmarks.id as bookmark_id, company_addresses.id as adr_id'
      ).joins("LEFT JOIN bookmarks ON (company_addresses.id = bookmarks.company_address_id AND bookmarks.user_id =
        #{current_user.id})").where(zip_code: params[:zip_codes])
    else
      @addresses = CompanyAddress.joins(:company).select(
          'companies.company_name, companies.company_size, companies.category ,company_addresses.street_number,
        company_addresses.street_indicator, company_addresses.street_type, company_addresses.street_label,
        company_addresses.zip_code, company_addresses.city, company_addresses.latitude, company_addresses.longitude,
        bookmarks.id as bookmark_id, company_addresses.id as adr_id'
      ).joins("LEFT JOIN bookmarks ON (company_addresses.id = bookmarks.company_address_id AND bookmarks.user_id =
        #{current_user.id})").all
    end
  end

  def departments
    @zipcodes = CompanyAddress.select(:zip_code).map(&:zip_code).uniq

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  # TODO : figure why you got the can't render twice error   ?  isn't redirect equivalent to return ?
  def create
    if !params[:session].nil? && !params[:session][:email].nil? && !params[:session][:password].nil?
      @user = User.find_by_email(params[:session][:email])
      if @user && @user.authenticate(params[:session][:password])
        session[:user_id] = @user.id
        redirect_to '/'
      else
        redirect_to login_path
        flash[:error] = "wrong login or password"
      end
    else
      redirect_to login_path
      flash[:error] = "wrong login or password"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:edit]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  def edit
    @user = User.find(session[:user_id])
  end

  def update
    @user = User.find(session[:user_id])

    if @user.update_attributes(:password_digest => BCrypt::Password.create(user_ud_params[:password_digest])) &&
        user_ud_params[:password_digest]!= user_ud_params[:password]
      flash[:success] = "password has been updated"
    elsif user_ud_params[:password_digest]!= user_ud_params[:password]
      render 'edit'
      flash[:error] = "passwords do not match"
    else
      render 'edit'
      flash[:error] = "something went  wrong"
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
  def user_ud_params
    params.require(:user).permit(:password_digest)
  end

end

app/helpers/address_helper.rb
module AddressHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/company_addresses_helper.rb
module CompanyAddressesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/company_addresses/departments.html.erb
<div class="container separator  text-center">
<%= form_tag("/addresses", method: "post") do %>
<div class="container center-page">
  <label for="info" > <% @zipcodes.each do |zip|  %>
      <%= label_tag(:q, zip) %>
      <%= check_box_tag('zip_codes[]',zip)%>

      </label> |

  <% end %>

    </div>
<%= submit_tag("Search") %>
<% end %>
</div>

app/views/company_addresses/index.html.erb
<div class="container" >
<table id="company_addresses" class="display" style="width:100%">
  <thead>
  <tr>
    <th>Company Name</th>
    <th>Company Size</th>
    <th>Category</th>
    <th>address</th>
    <th>latitude</th>
    <th>longitude</th>
    <th>location</th>
    <th>bookmarked</th>
  </tr>
  </thead>
  <tbody>
  <% @addresses.each do |address|  %>
    <tr>
      <td><%= address.company_name %></td>
      <td><%= address.company_size %></td>
      <td><%= address.category %></td>
      <td><%= address.street_number %>&nbsp;
        <%= address.street_indicator %>&nbsp;
        <%= address.street_type  %>&nbsp;
        <%= address.street_label %>&nbsp;
        <%= address.zip_code %>&nbsp;
        <%= address.city  %></td>
      <td><%= address.latitude %></td>
      <td><%= address.longitude %></td>
      <td><%= link_to "locate", "http://www.google.com/maps/place/"+address.latitude+","+address.longitude, target: :_blank %></td>
      <td>
        <% if address.bookmark_id.nil? %>
          <%= link_to "Add to bookmarks", bookmark_path( company_address_id: address.adr_id), method: :post, :onclick =>'this.href=#'  %>
        <% else %>
          <%= link_to "remove from bookmarks", unmark_path( company_address_id: address.adr_id), method: :post, :data => {:confirm => 'Are you sure?'}, :onclick =>'this.href=#'%>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
  <tfoot>
  <tr>
    <th>Company Name</th>
    <th>Company Size</th>
    <th>Category</th>
    <th>address</th>
    <th>latitude</th>
    <th>longitude</th>
    <th>location</th>
    <th>bookmarked</th>
  </tr>
  </tfoot>
</table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestProject52</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/fixedheader/3.1.5/css/fixedHeader.dataTables.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/fixedheader/3.1.5/js/dataTables.fixedHeader.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

  </head>

  <body>


    <%= yield %>
    <footer  class="footer ">
      <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-danger alert-dismissible fade show alert-<%= key %>" role="alert"> <%= value %></div>
    <% end %>

    <% if current_user %>
<div class="text-center" >
          Hello <%= current_user.email %>


          <%= link_to "Account", reset_path, method: "get" %> | <%= link_to "Log out", logout_path, method: "delete" %>
</div>
    <% else %>

        <%= link_to "Login", 'login' %></a> |<%= link_to "Signup", 'signup' %></a>
        </div>
          </div>
      </footer>
    <% end %>


  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/edit.html.erb
<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->

    <!-- Icon -->
    <div class="fadeIn first">
      <img src="https://envoy.com/images/icons/pin.svg" id="icon" alt="User Icon" />
      <h1>Company Finder</h1>
    </div>
    <div class="login">
    <%= form_for(@user) do |f| %>

      <%= f.label :password %>
      <%= f.password_field :password_digest, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
    </div>
  </div>

</div>

app/views/users/new.html.erb
<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->

    <!-- Icon -->
    <div class="fadeIn first">
      <img src="https://envoy.com/images/icons/pin.svg" id="icon" alt="User Icon" />
      <h1>Company Finder</h1>
    </div>
    <div class="login">
      <h1>Sign up</h1>
      <%= form_for(@user) do |f| %>
        <%= f.email_field :email, :placeholder => "Email" %>
        <%= f.password_field :password, :placeholder => "Password" %>
        <%= f.submit "Create an account", class: "btn-submit" %>
      <% end %>
    </div>
  </div>

</div>